prompt_order = [
	"time",
	"username",
	"hostname",
	"directory",
	"git_branch",
	"git_commit",
	"git_state",
	"git_status",
	"package",
	"nodejs",
	"python",
	"java",
	"line_break",
	"character",
]
add_newline = false
[time]
disabled = false
show_always = true
use_12hr = true
style = "blue bold"
[character]
symbol = "$ "
[hostname]
ssh_only = false
disabled = false
style = "green bold"
show_always = true
[username]
disabled = false
show_always = true
style_user = "red bold"
style_root = "red bold"
[directory]
disabled = false
show_always = true
style = "yellow bold"
